# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Weltliteratur
tagline:          'black market for the digital humanities'
description:      'black market for the digital humanities'
url:              http://blog.weltliteratur.net
baseurl:          /

author:
  name:           'Frank, Robert & friends'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/weltliteratur
