# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:             [jekyll-paginate]

# Permalinks
permalink:        /:title/

# Setup
name:             'A Black Market for the Digital Humanities'
title:            weltliteratur.net
tagline:          'A Black Market for the Digital Humanities'
description:      'A Black Market for the Digital Humanities'
url:              http://weltliteratur.net
baseurl:          /
base: 	      	  http://weltliteratur.net

author:           Frank, Robert & friends

authors:
  robert:
    name: Robert Jäschke
    display_name: Robert
    gravatar: 2c9c581ae0a3d3590563d9f4120b1861
    email: jaeschke@L3S.de
    web: https://www.kbs.uni-hannover.de/~jaeschke/
    twitter: 
    github: rjoberon
    description: Professor for Web Science at the University of Hanover.
  mathias:
    name: Mathias Göbel
    display_name: Mathias
    email: goebel@sub.uni-goettingen.de
    web: http://mathias-goebel.github.io/
    twitter: goebel_m
    github: mathias-goebel
    gravatar: 6cfefa5456ac7fd4f39298f29c05fae8
    description: code follows function
  frank:
    name: Frank Fischer
    display_name: Frank
    gravatar: 0e4f5ff81e5b1b1976c939b57207bb2d
    email: frank.fischer@zentr.uni-goettingen.de
    web: http://www.gcdh.de/frank.fischer
    twitter: umblaetterer
    github: lehkost
    description: Doing Digital Humanities at the Higher School of Economics in Moscow.
  christopher:
    name: Christopher Johnson
    display_name: Christopher
    gravatar: 1677f037a1fd040cb5574babb9e24936
    email: 
    web: 
    twitter: 
    github: christopher-johnson
    description: Researcher for the Göttingen Academy of Sciences.
  ubbo:
    name: Ubbo Veentjer
    display_name: Ubbo
    gravatar: 
    email: veentjer@sub.uni-goettingen.de
    web: 
    twitter: 
    github: ubbo
    description: "Den Code dokumentieren wir später."

paginate:         10

# Custom vars
version:          0.0.1
disqus:		  weltliteratur
github:
  repo:           https://github.com/weltliteratur
