# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:             [jekyll-paginate]

# Permalinks
permalink:        title

# Setup
name:             'A Black Market for the Digital Humanities'
title:            weltliteratur.net
tagline:          'A Black Market for the Digital Humanities'
description:      'A Black Market for the Digital Humanities'
url:              http://weltliteratur.net
baseurl:          /
base: http://weltliteratur.net/

author:           Frank, Robert & friends

authors:
  Frank:	http://www.gcdh.de/frank.fischer
  Robert:	http://www.kbs.uni-hannover.de/~jaeschke/
  Mathias:	http://mathias-goebel.github.io

paginate:         10

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/weltliteratur
