# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:             [jekyll-paginate]

# Permalinks
permalink:        /:title/

# Setup
name:             'A Black Market for the Digital Humanities'
title:            weltliteratur.net
tagline:          'A Black Market for the Digital Humanities'
description:      'A Black Market for the Digital Humanities'
keywords:	  digital humanities, weltliteratur, world literature, blog
url:              https://weltliteratur.net
baseurl:          /
base: 	      	  https://weltliteratur.net

author:           Frank, Robert & friends

authors:
  robert:
    name: Robert Jäschke
    display_name: Robert
    img: /images/rj.jpg
    email: jaeschke@L3S.de
    web: https://amor.cms.hu-berlin.de/~jaeschkr/
    orcid: 0000-0003-3271-9653
    twitter:
    github: rjoberon
    description: Professor at Humboldt-Universität zu Berlin.
  mathias:
    name: Mathias Göbel
    display_name: Mathias
    email: goebel@sub.uni-goettingen.de
    web: http://mathias-goebel.github.io/
    twitter: goebel_m
    github: mathias-goebel
    img: /images/mg.png
    description: code follows function
  frank:
    name: Frank Fischer
    display_name: Frank
    img: /images/ff.png
    email: ffischer@hse.ru
    orcid: 0000-0003-2419-6629
    web: https://www.hse.ru/en/org/persons/182492735
    twitter: umblaetterer
    github: lehkost
    description: Doing Digital Humanities at Higher School of Economics in Moscow. Director of DARIAH-EU.
  christopher:
    name: Christopher Johnson
    display_name: Christopher
    img: /images/cj.jpg
    email: 
    web: 
    twitter: 
    github: christopher-johnson
    description: Researcher for the Göttingen Academy of Sciences.
  peer:
    name: Peer Trilcke
    display_name: Peer
    img: /images/pt.jpg
    email: trilcke@uni-potsdam.de
    web: http://www.peertrilcke.de/
    twitter: peertrilcke
    github: peertrilcke
    description: Assistant Professor (Juniorprofessor) of Modern German Literature and Media at University of Potsdam.
  ubbo:
    name: Ubbo Veentjer
    display_name: Ubbo
    email: veentjer@sub.uni-goettingen.de
    web:
    twitter:
    github: ubbo
    description: "Den Code dokumentieren wir später."
  jannik:
    name: Jannik Strötgen
    display_name: Jannik
    email: jannik.stroetgen@mpi-inf.mpg.de
    web: https://people.mpi-inf.mpg.de/~jstroetge/
    twitter: jannikstroetgen
    github: JannikStroetgen
    description: Researcher at the Max Planck Institute for Informatics.
  angelika:
    name: Angelika Hechtl
    display_name: Angelika
    img: /images/ah.jpg
    email: angelika.hechtl@wu.ac.at
    web: http://www.likeanga.at/
    twitter: angelikah
    github: likeanga
    orcid: 0000-0001-6104-7484
    description: Doing Linguistics and Digital Humanities at WU Wien.
  ingo:
    name: Ingo Börner
    display_name: Ingo
    img: /images/ib.jpg
    email: ingo.boerner@univie.ac.at
    web: 
    twitter: ingoboerner
    github: ingoboerner
    orcid: 0000-0001-8294-2541
    description: …
  galina:
    name: Galina Ryazanskaya
    display_name: Galina
    img: /images/gr.jpg
    email: galka1999@gmail.com
    web: 
    twitter: 
    github: 
    description: HSE, Moscow.
  alena:
    name: Alena Shchevyeva
    display_name: Alena
    email: 
    web: 
    twitter: 
    github: 
    description: HSE, Moscow.
  maria:
    name: Maria Suvorova
    display_name: Maria
    email: 
    web: 
    twitter: 
    github: brouhahaha
    description: HSE, Moscow.
  eduard:
    name: Eduard Grigoryev
    display_name: Eduard
    img: /images/eg.jpg
    email: 
    web: 
    twitter: happypuffin7
    github: ldsad7
    orcid: 
    description: HSE, Moscow.
  laure:
    name: Laure Barbot
    display_name: Laure
    img: /images/lb.jpg
    email: 
    web: https://cmb.hu-berlin.de/en/team/profil/laure-barbot/
    twitter: 
    github: 
    orcid: 0000-0002-6008-7959
    description: Project officer at DARIAH-EU, Berlin.
  yoann:
    name: Yoann Moranville
    display_name: Yoann
    email: 
    web: 
    twitter: 
    github: yoannspace
    orcid: 0000-0002-3502-1667
    description: Developer at DARIAH. Technical Coordinator of OPERAS.
  ivan:
    name: Ivan Pozdniakov
    display_name: Ivan
    email: 
    web: 
    twitter: ivanpoz70536140
    github: Pozdniakov
    orcid: 
    description: Higher School of Economics, Moscow.
    

paginate:         10

# Custom vars
version:          0.0.1
# disqus:           
github:
repo:             https://github.com/weltliteratur
