# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:             [jekyll-paginate]

# Permalinks
permalink:        /:title/

# Setup
name:             'A Black Market for the Digital Humanities'
title:            weltliteratur.net
tagline:          'A Black Market for the Digital Humanities'
description:      'A Black Market for the Digital Humanities'
url:              http://weltliteratur.net
baseurl:          /
base: 	      	  http://weltliteratur.net

author:           Frank, Robert & friends

authors:
  robert:
    name: Robert Jäschke
    display_name: Robert
    gravatar: 2c9c581ae0a3d3590563d9f4120b1861
    email: jaeschke@L3S.de
    web: https://www.sheffield.ac.uk/is/staff/jaeschke
    twitter:
    github: rjoberon
    description: Senior Lecturer at the University of Sheffield.
  mathias:
    name: Mathias Göbel
    display_name: Mathias
    email: goebel@sub.uni-goettingen.de
    web: http://mathias-goebel.github.io/
    twitter: goebel_m
    github: mathias-goebel
    gravatar: 6cfefa5456ac7fd4f39298f29c05fae8
    description: code follows function
  frank:
    name: Frank Fischer
    display_name: Frank
    gravatar: 0e4f5ff81e5b1b1976c939b57207bb2d
    email: ffischer@hse.ru
    web: https://www.hse.ru/en/org/persons/182492735
    twitter: umblaetterer
    github: lehkost
    description: Doing Digital Humanities at the Higher School of Economics in Moscow.
  christopher:
    name: Christopher Johnson
    display_name: Christopher
    gravatar: 1677f037a1fd040cb5574babb9e24936
    email: 
    web: 
    twitter: 
    github: christopher-johnson
    description: Researcher for the Göttingen Academy of Sciences.
  peer:
    name: Peer Trilcke
    display_name: Peer
    gravatar: 3995a022afbaf45c8afdd0514d099e63
    email: trilcke@uni-potsdam.de
    web: http://www.peertrilcke.de/
    twitter: peertrilcke
    github: peertrilcke
    description: Assistant Professor (Juniorprofessor) of Modern German Literature and Media at the University of Potsdam.
  ubbo:
    name: Ubbo Veentjer
    display_name: Ubbo
    gravatar:
    email: veentjer@sub.uni-goettingen.de
    web:
    twitter:
    github: ubbo
    description: "Den Code dokumentieren wir später."
  jannik:
    name: Jannik Strötgen
    display_name: Jannik
    gravatar: 
    email: jannik.stroetgen@mpi-inf.mpg.de
    web: https://people.mpi-inf.mpg.de/~jstroetge/
    twitter: jannikstroetgen
    github: JannikStroetgen
    description: Researcher at the Max Planck Institute for Informatics.

paginate:         10

# Custom vars
version:          0.0.1
disqus:           weltliteratur
github:
repo:             https://github.com/weltliteratur
