# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:             [jekyll-paginate]

# Permalinks
permalink:        /:title/

# Setup
name:             'A Black Market for the Digital Humanities'
title:            weltliteratur.net
tagline:          'A Black Market for the Digital Humanities'
description:      'A Black Market for the Digital Humanities'
url:              http://weltliteratur.net
baseurl:          /
base: http://weltliteratur.net/

author:           Frank, Robert & friends

authors:
  frank:
    name: Frank Fischer
    display_name: Frank
    gravatar: 0e4f5ff81e5b1b1976c939b57207bb2d
    email: frank.fischer@sub.uni-goettingen.de
    web: http://www.umblaetterer.de
    twitter: umblaetterer
    github: lehkost
  Robert:	http://www.kbs.uni-hannover.de/~jaeschke/
  Mathias:	http://mathias-goebel.github.io

paginate:         10

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/weltliteratur
