# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:             [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            weltliteratur.net
tagline:          'A Black Market for the Digital Humanities'
description:      'A Black Market for the Digital Humanities'
url:              http://blog.weltliteratur.net
baseurl:          /

author:
  name:           'Frank, Robert & friends'
  url:            https://twitter.com/mdo

authors:
  Frank:          http://www.gcdh.de/frank.fischer
  Robert:	        http://www.kbs.uni-hannover.de/~jaeschke/

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/weltliteratur
